project:
  type: website

website:
  title: "hrspx : : blog"
  description: "This is Bart Klimowski personal Blog."
  navbar:
    right:
      - about.qmd
      - text: Archive
        href: archive.qmd
format:
  html:
    theme: 
      - journal
      - custom.scss
    css: styles.css



